from ibmcom/ace:latest

USER aceuser
RUN echo $PWD

RUN mkdir -p /home/aceuser/db2cli_odbc_driver
COPY ibm_data_server_driver_for_odbc_cli_linuxx64_v11.5.tar.gz /home/aceuser/db2cli_odbc_driver
WORKDIR /home/aceuser/db2cli_odbc_driver
RUN echo $PWD
RUN tar -xvzf ibm_data_server_driver_for_odbc_cli_linuxx64_v11.5.tar.gz

#COPY odbc.ini /home/aceuser/ace-server/odbc.ini
#COPY odbcinst.ini /var/mqsi/odbc/odbcinst.ini
#COPY db2cli.ini /var/mqsi/odbc/db2cli.ini

ENV ODBCINI /home/aceuser/ace-server/odbc.ini
ENV ODBCSYSINI /home/aceuser/initial-config/odbcini/
ENV DB2CLIINIPATH /home/aceuser/initial-config/odbcini/
ENV LD_LIBRARY_PATH /home/aceuser/db2cli_odbc_driver/odbc_cli/clidriver/lib
ENV IE02_PATH=/opt/IBM/ace-11.0.0.5/ie02
WORKDIR /home/aceuser





 


