---
ResourceManagers:
  JVM:
    jvmDebugPort: 7002 

# Defaults:
#   Policies:
#     HTTPSConnector: 'HTTPS'

Defaults:
 defaultApplication: ''       # Name a default application under which independent resources will be placed
 policyProject: 'DefaultPolicies'   # Name of the Policy project that will be used for unqualified Policy references
 Policies:
   # Set default policy names, optionally qualified with a policy project as {policy project}:name
   HTTPSConnector: 'HTTPS'          # Default HTTPS connector policy
